export const factoryAbi = [
  {
    inputs: [{ internalType: 'address', name: '_curatorImpl', type: 'address' }],
    stateMutability: 'payable',
    type: 'constructor',
  },
  { inputs: [], name: 'ADDRESS_ZERO', type: 'error' },
  { inputs: [], name: 'ALREADY_INITIALIZED', type: 'error' },
  { inputs: [], name: 'DELEGATE_CALL_FAILED', type: 'error' },
  { inputs: [], name: 'INITIALIZING', type: 'error' },
  { inputs: [], name: 'INVALID_TARGET', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'impl', type: 'address' }],
    name: 'INVALID_UPGRADE',
    type: 'error',
  },
  { inputs: [], name: 'NOT_INITIALIZING', type: 'error' },
  { inputs: [], name: 'ONLY_CALL', type: 'error' },
  { inputs: [], name: 'ONLY_DELEGATECALL', type: 'error' },
  { inputs: [], name: 'ONLY_OWNER', type: 'error' },
  { inputs: [], name: 'ONLY_PENDING_OWNER', type: 'error' },
  { inputs: [], name: 'ONLY_PROXY', type: 'error' },
  { inputs: [], name: 'ONLY_UUPS', type: 'error' },
  { inputs: [], name: 'UNSUPPORTED_UUID', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'curator', type: 'address' },
      { indexed: false, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'address', name: 'deployer', type: 'address' },
    ],
    name: 'CuratorDeployed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: '', type: 'address' }],
    name: 'HasNewMetadataRenderer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'version', type: 'uint256' },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'canceledOwner', type: 'address' },
    ],
    name: 'OwnerCanceled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'pendingOwner', type: 'address' },
    ],
    name: 'OwnerPending',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'prevOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'implFrom', type: 'address' },
      { indexed: false, internalType: 'address', name: 'implTo', type: 'address' },
    ],
    name: 'RegisteredUpgradePath',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'impl', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    inputs: [],
    name: 'acceptOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_baseImpl', type: 'address' },
      { internalType: 'address', name: '_newImpl', type: 'address' },
    ],
    name: 'addValidUpgradePath',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'cancelOwnershipTransfer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'curatorHash',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'curatorImpl',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'defaultMetadataRenderer',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'curationManager', type: 'address' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'address', name: 'tokenPass', type: 'address' },
      { internalType: 'bool', name: 'initialPause', type: 'bool' },
      { internalType: 'uint256', name: 'curationLimit', type: 'uint256' },
      { internalType: 'address', name: 'renderer', type: 'address' },
      { internalType: 'bytes', name: 'rendererInitializer', type: 'bytes' },
      {
        components: [
          { internalType: 'address', name: 'curatedAddress', type: 'address' },
          { internalType: 'uint96', name: 'selectedTokenId', type: 'uint96' },
          { internalType: 'address', name: 'curator', type: 'address' },
          { internalType: 'uint16', name: 'curationTargetType', type: 'uint16' },
          { internalType: 'int32', name: 'sortOrder', type: 'int32' },
          { internalType: 'bool', name: 'hasTokenId', type: 'bool' },
          { internalType: 'uint16', name: 'chainId', type: 'uint16' },
        ],
        internalType: 'struct ICurator.Listing[]',
        name: 'listings',
        type: 'tuple[]',
      },
    ],
    name: 'deploy',
    outputs: [{ internalType: 'address', name: 'curator', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_owner', type: 'address' },
      { internalType: 'address', name: '_defaultMetadataRenderer', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_baseImpl', type: 'address' },
      { internalType: 'address', name: '_newImpl', type: 'address' },
    ],
    name: 'isValidUpgrade',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'safeTransferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_renderer', type: 'address' }],
    name: 'setDefaultMetadataRenderer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_newImpl', type: 'address' }],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_newImpl', type: 'address' },
      { internalType: 'bytes', name: '_data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
] as const
