export const curationTargetTypes = {
  '0': 'CURATION_TYPE_GENERIC',
  '1': 'CURATION_TYPE_NFT_CONTRACT',
  '2': 'CURATION_TYPE_CONTRACT',
  '3': 'CURATION_TYPE_CURATION_CONTRACT',
  '4': 'CURATION_TYPE_NFT_ITEM',
  '5': 'CURATION_TYPE_WALLET',
  '6': 'CURATION_TYPE_ZORA_EDITION',
}
